language: php

php:
  - 7.1
  - 7.2

script: ./vendor/bin/tester -c ./tests/php-unix.ini ./tests/PixidosTests/

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

